import AutoGeneratedPlaylist from '#/models/autoGeneratedPlaylist';
import cron from 'node-cron';
import Audio from '#/models/audio';

// the five fields in the cron syntax represent
// minutes, hours, day of the month, month,
// day of the week respectively.

const generatePlaylist = async () => {
    const result = await Audio.aggregate([
        {
          $sort: { likes: -1 }
        },
        {
          $sample: { size: 20 }
        },
        {
          $group: {
            _id: "$category",
            audios: { $push: "$$ROOT._id" }
          }
        }
      ]);
  
      result.map(async (item) => {
        await AutoGeneratedPlaylist.updateOne(
          { title: item._id },
          { $set: { items: item.audios } },
          { upsert: true }
        );
      })
}

cron.schedule("0 0 * * *", async () => {
    // this will run every 24 hours
    await generatePlaylist();
});
