import { models, ObjectId, Schema, model, Model } from "mongoose"

interface AutoPlaylistDocument {
    title: string;
    items: ObjectId[];
}

const autoPlaylistSchema = new Schema<AutoPlaylistDocument>({
    title: {
        type: String,
        required: true
    },
    items: [{
        type: Schema.Types.ObjectId,
        required: true,
        ref: "Audio"
    }],
}, {
    timestamps: true
});

const AutoGeneratedPlaylist = models.AutoGeneratedPlaylist || model("AutoGeneratedPlaylist", autoPlaylistSchema);

export default AutoGeneratedPlaylist as Model<AutoPlaylistDocument>;
